services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    # Host= postgres-postgresql:5432;Database=data;Username=user;Password=705399f1663ba8e0bbf55fdab8b7b765;
    environment:
      - POSTGRES_DB=data
      - POSTGRES_PASSWORD=705399f1663ba8e0bbf55fdab8b7b765
      - POSTGRES_USER=user

  bored_api:
    build:
      context: .
      dockerfile: Dockerfile
#    command: pip install -r requirements.txt && ./manage.py collectstatic --noinput && \\
#        ./manage.py runserver 0.0.0.0:8000
#    command: >
#      bash -c "pip install -r requirements.txt && ./manage.py collectstatic --noinput && \\
#        gunicorn bored.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - type: bind
        source: .
        target: /code/
    ports:
      - 8000:8000
    depends_on:
      - db

