services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  bored_api:
    build:
      context: .
      dockerfile: Dockerfile
#    command: pip install -r requirements.txt && ./manage.py collectstatic --noinput && \\
#        ./manage.py runserver 0.0.0.0:8000
#    command: >
#      bash -c "pip install -r requirements.txt && ./manage.py collectstatic --noinput && \\
#        gunicorn bored.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - type: bind
        source: .
        target: /code/
    ports:
      - 8000:8000
    depends_on:
      - db

