# Generated by Django 5.0.3 on 2025-06-29 16:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('activity_type', models.CharField(max_length=120)),
                ('participants', models.IntegerField()),
                ('price', models.FloatField()),
                ('link', models.URLField(blank=True, null=True)),
                ('key', models.CharField(max_length=50)),
                ('accessibility', models.CharField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('availability', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('duration', models.CharField(blank=True, null=True)),
                ('kidFriendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('availability__gte', 0.0), ('availability__lte', 1.0)), name='myfloat_range'),
        ),
    ]
